[2024-11-05T21:22:56.490-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_with_custom_email_alerts1.task_merge_participantstatus_demographics_biospecimen_analysis manual__2024-11-06T02:22:10.425973+00:00 [queued]>
[2024-11-05T21:22:56.498-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_with_custom_email_alerts1.task_merge_participantstatus_demographics_biospecimen_analysis manual__2024-11-06T02:22:10.425973+00:00 [queued]>
[2024-11-05T21:22:56.498-0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-11-05T21:22:56.635-0500] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): task_merge_participantstatus_demographics_biospecimen_analysis> on 2024-11-06 02:22:10.425973+00:00
[2024-11-05T21:22:56.639-0500] {standard_task_runner.py:57} INFO - Started process 66269 to run task
[2024-11-05T21:22:56.644-0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline_with_custom_email_alerts1', 'task_merge_participantstatus_demographics_biospecimen_analysis', 'manual__2024-11-06T02:22:10.425973+00:00', '--job-id', '393', '--raw', '--subdir', 'DAGS_FOLDER/try1.py', '--cfg-path', '/tmp/tmpigj212yd']
[2024-11-05T21:22:56.646-0500] {standard_task_runner.py:85} INFO - Job 393: Subtask task_merge_participantstatus_demographics_biospecimen_analysis
[2024-11-05T21:22:56.756-0500] {task_command.py:416} INFO - Running <TaskInstance: data_pipeline_with_custom_email_alerts1.task_merge_participantstatus_demographics_biospecimen_analysis manual__2024-11-06T02:22:10.425973+00:00 [running]> on host mrudula-OMEN-by-HP-Laptop
[2024-11-05T21:22:56.957-0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline_with_custom_email_alerts1' AIRFLOW_CTX_TASK_ID='task_merge_participantstatus_demographics_biospecimen_analysis' AIRFLOW_CTX_EXECUTION_DATE='2024-11-06T02:22:10.425973+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-06T02:22:10.425973+00:00'
[2024-11-05T21:22:56.997-0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/mrudula/airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/mrudula/airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mrudula/airflow/dags/try1.py", line 146, in merge_biospecimen_with_participant
    raise ValueError("biospecimen_analysis is None. Check the task 'task_clean_filtered_biospecimen_analysis'.")
ValueError: biospecimen_analysis is None. Check the task 'task_clean_filtered_biospecimen_analysis'.
[2024-11-05T21:22:57.002-0500] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=data_pipeline_with_custom_email_alerts1, task_id=task_merge_participantstatus_demographics_biospecimen_analysis, execution_date=20241106T022210, start_date=20241106T022256, end_date=20241106T022257
[2024-11-05T21:22:57.271-0500] {standard_task_runner.py:104} ERROR - Failed to execute job 393 for task task_merge_participantstatus_demographics_biospecimen_analysis (biospecimen_analysis is None. Check the task 'task_clean_filtered_biospecimen_analysis'.; 66269)
[2024-11-05T21:22:57.296-0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-05T21:22:57.317-0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
