[2024-11-05T23:38:32.672-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_with_custom_email_alerts1.clean_preprocess_eda manual__2024-11-06T04:36:57.747134+00:00 [queued]>
[2024-11-05T23:38:32.678-0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_with_custom_email_alerts1.clean_preprocess_eda manual__2024-11-06T04:36:57.747134+00:00 [queued]>
[2024-11-05T23:38:32.678-0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-11-05T23:38:32.822-0500] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): clean_preprocess_eda> on 2024-11-06 04:36:57.747134+00:00
[2024-11-05T23:38:32.826-0500] {standard_task_runner.py:57} INFO - Started process 94961 to run task
[2024-11-05T23:38:32.828-0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline_with_custom_email_alerts1', 'clean_preprocess_eda', 'manual__2024-11-06T04:36:57.747134+00:00', '--job-id', '558', '--raw', '--subdir', 'DAGS_FOLDER/try1.py', '--cfg-path', '/tmp/tmp4q6u65lu']
[2024-11-05T23:38:32.829-0500] {standard_task_runner.py:85} INFO - Job 558: Subtask clean_preprocess_eda
[2024-11-05T23:38:32.934-0500] {task_command.py:416} INFO - Running <TaskInstance: data_pipeline_with_custom_email_alerts1.clean_preprocess_eda manual__2024-11-06T04:36:57.747134+00:00 [running]> on host mrudula-OMEN-by-HP-Laptop
[2024-11-05T23:38:33.125-0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_pipeline_with_custom_email_alerts1' AIRFLOW_CTX_TASK_ID='clean_preprocess_eda' AIRFLOW_CTX_EXECUTION_DATE='2024-11-06T04:36:57.747134+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-06T04:36:57.747134+00:00'
[2024-11-05T23:38:33.404-0500] {logging_mixin.py:151} WARNING - /home/mrudula/airflow/dags/try1.py:307 FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.
[2024-11-05T23:38:33.415-0500] {logging_mixin.py:151} WARNING - /home/mrudula/airflow/dags/try1.py:309 FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.
[2024-11-05T23:38:33.868-0500] {python.py:194} INFO - Done. Returned value was:         Participant_ID  COHORT ENROLL_DATE  ...   PATNO  EVENT_ID  NUPSOURC
0                 3000       2  2011-02-01  ...    3000        BL       1.0
1                 3000       2  2011-02-01  ...    3000       V04       1.0
2                 3000       2  2011-02-01  ...    3000       V06       1.0
3                 3000       2  2011-02-01  ...    3000       V08       1.0
4                 3000       2  2011-02-01  ...    3000       V10       1.0
...                ...     ...         ...  ...     ...       ...       ...
112743          402314       1  2024-10-01  ...  402314        BL       3.0
112744          402314       1  2024-10-01  ...  402314        BL       3.0
112745          402314       1  2024-10-01  ...  402314        BL       1.0
112746          402314       1  2024-10-01  ...  402314        BL       1.0
112747          402314       1  2024-10-01  ...  402314        BL       1.0

[112284 rows x 14 columns]
[2024-11-05T23:38:34.130-0500] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=data_pipeline_with_custom_email_alerts1, task_id=clean_preprocess_eda, execution_date=20241106T043657, start_date=20241106T043832, end_date=20241106T043834
[2024-11-05T23:38:34.323-0500] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-11-05T23:38:34.336-0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
